import { Job, Student, Organization, Application } from "@/types";

export const mockStudent: Student = {
  id: "s1",
  name: "Alex Petrov",
  email: "alex.petrov@students.ukim.mk",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
  university: "Ss. Cyril and Methodius University",
  major: "Computer Science",
  year: "3rd Year",
  gpa: "9.2",
  bio: "Passionate CS student interested in building products that matter. Looking for software engineering internships.",
  skills: ["React", "TypeScript", "Python", "Node.js", "Figma"],
  linkedin: "linkedin.com/in/alexpetrov",
  github: "github.com/alexpetrov",
};

export const mockOrg: Organization = {
  id: "11111111-1111-1111-1111-111111111111",
  name: "TechMK",
  email: "hr@techmk.com",
  avatar: "https://api.dicebear.com/7.x/initials/svg?seed=TM",
  industry: "Software",
  size: "50–200",
  location: "Skopje, MK",
  website: "techmk.com",
  description:
    "TechMK is a fast-growing software company building SaaS products for the Balkans market.",
  founded: "2018",
  verified: true,
  hiresCount: 23,
  responseTime: "Usually responds in 2–3 days",
  activeThisWeek: true,
};

export const mockOrganizations: Organization[] = [
  mockOrg,
  {
    id: "o2",
    name: "Alkaloid",
    email: "careers@alkaloid.com.mk",
    industry: "Pharma & Tech",
    size: "1000+",
    location: "Skopje, MK",
    description: "Leading pharmaceutical and technology company in the region.",
    founded: "1936",
    verified: true,
    hiresCount: 61,
    responseTime: "Usually responds in 5–7 days",
    activeThisWeek: true,
  },
  {
    id: "o3",
    name: "Sorsix",
    email: "jobs@sorsix.com",
    industry: "Software",
    size: "50–200",
    location: "Skopje, MK",
    description: "Software consulting and product development.",
    founded: "2012",
    verified: true,
    hiresCount: 34,
    responseTime: "Usually responds in 3–5 days",
    activeThisWeek: false,
  },
  {
    id: "o4",
    name: "Brainster",
    email: "careers@brainster.co",
    industry: "EdTech",
    size: "10–50",
    location: "Skopje, MK",
    description: "The leading tech education company in the Western Balkans.",
    founded: "2017",
    verified: true,
    hiresCount: 18,
    responseTime: "Usually responds in 2–4 days",
    activeThisWeek: true,
  },
  {
    id: "o5",
    name: "Netcetera",
    email: "careers@netcetera.com",
    industry: "Software",
    size: "500–1000",
    location: "Skopje, MK",
    description: "Swiss software company with a major development hub in Macedonia.",
    founded: "1999",
    verified: true,
    hiresCount: 89,
    responseTime: "Usually responds in 1–2 weeks",
    activeThisWeek: true,
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    orgId: "o1",
    orgName: "TechMK",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TM",
    title: "Frontend Engineering Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€400–600/mo",
    description:
      "Join our product team to build beautiful, fast web interfaces. You'll work directly with senior engineers on real features shipped to thousands of users. No ticket monkey work — you'll own small features end to end.",
    requirements: [
      "Experience with React or Vue",
      "Basic TypeScript knowledge",
      "Eye for design and UX",
      "Available 20–40h/week",
    ],
    tags: ["React", "TypeScript", "Tailwind", "Frontend"],
    status: "open",
    postedAt: "2026-04-10",
    deadline: "2026-05-01",
    daysUntilDeadline: 13,
    applicantCount: 12,
    verified: true,
    featured: true,
    timeline: "2–3 weeks from application to offer",
    hiringProcess: [
      { step: 1, label: "CV Review", description: "We review your profile within 3 days." },
      { step: 2, label: "Short Intro Call", description: "15-min call to get to know you." },
      { step: 3, label: "Take-home Task", description: "Small frontend task, ~2–3 hours." },
      { step: 4, label: "Offer", description: "We move fast — decision within a week." },
    ],
  },
  {
    id: "j2",
    orgId: "o3",
    orgName: "Sorsix",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=SO",
    title: "Backend Developer Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€350–500/mo",
    description:
      "Work on backend services powering enterprise clients across Europe. You'll learn about scalable architecture, REST APIs, and cloud infrastructure while shipping real code to production.",
    requirements: [
      "Java or Kotlin basics",
      "Understanding of REST APIs",
      "Comfortable with Git",
      "Eager to learn",
    ],
    tags: ["Java", "Spring Boot", "Backend", "REST", "AWS"],
    status: "open",
    postedAt: "2026-04-08",
    deadline: "2026-04-30",
    daysUntilDeadline: 12,
    applicantCount: 8,
    verified: true,
    timeline: "3–4 weeks end to end",
    hiringProcess: [
      { step: 1, label: "Application Review", description: "CV and GitHub screened within 5 days." },
      { step: 2, label: "Technical Interview", description: "45-min technical call with the team." },
      { step: 3, label: "Team Interview", description: "Culture and fit conversation." },
      { step: 4, label: "Offer", description: "Decision communicated within 3 days." },
    ],
  },
  {
    id: "j3",
    orgId: "o5",
    orgName: "Netcetera",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=NC",
    title: "Mobile Developer Intern (iOS/Android)",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€500–700/mo",
    description:
      "Build real mobile features for millions of users across Europe. You'll be embedded in a cross-functional team from day one, working on apps used in banking and fintech.",
    requirements: [
      "Basic Swift or Kotlin experience",
      "Passion for mobile UX",
      "Strong fundamentals in OOP",
      "Available full-time",
    ],
    tags: ["iOS", "Android", "Swift", "Kotlin", "Mobile"],
    status: "open",
    postedAt: "2026-04-05",
    deadline: "2026-05-15",
    daysUntilDeadline: 27,
    applicantCount: 24,
    verified: true,
    featured: true,
    timeline: "3–5 weeks from first contact to start",
    hiringProcess: [
      { step: 1, label: "CV Screen", description: "HR reviews within 7 days." },
      { step: 2, label: "Technical Task", description: "Small mobile coding task, ~4 hours." },
      { step: 3, label: "Panel Interview", description: "Technical + HR panel, 1 hour." },
      { step: 4, label: "Offer & Onboarding", description: "Start within 2 weeks of offer." },
    ],
  },
  {
    id: "j4",
    orgId: "o4",
    orgName: "Brainster",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=BR",
    title: "UX/UI Design Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€300–450/mo",
    description:
      "Help shape the learning experience for thousands of students. Work in Figma, run user interviews, and iterate on designs weekly. Your work ships — no mockups sitting in a drawer.",
    requirements: [
      "Figma proficiency",
      "Portfolio of UI work (2+ projects)",
      "Understanding of user-centered design",
      "Bonus: basic HTML/CSS",
    ],
    tags: ["Figma", "UX", "UI", "Design", "EdTech", "Prototyping"],
    status: "open",
    postedAt: "2026-04-12",
    deadline: "2026-04-28",
    daysUntilDeadline: 10,
    applicantCount: 19,
    verified: true,
    timeline: "1–2 weeks from application to start",
    hiringProcess: [
      { step: 1, label: "Portfolio Review", description: "We look at your Figma work within 3 days." },
      { step: 2, label: "Design Challenge", description: "Short redesign exercise, ~2 hours." },
      { step: 3, label: "Offer", description: "Fast process — usually done in under 2 weeks." },
    ],
  },
  {
    id: "j5",
    orgId: "o2",
    orgName: "Alkaloid",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=AL",
    title: "Data Analyst Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€400–550/mo",
    description:
      "Analyze production and sales data to support business decisions across the company. Work with SQL, Python, and internal BI tools on datasets that drive million-euro decisions.",
    requirements: [
      "SQL basics",
      "Python or R for data analysis",
      "Strong analytical thinking",
      "Excel proficiency",
    ],
    tags: ["SQL", "Python", "Data", "Analytics", "BI", "Excel"],
    status: "open",
    postedAt: "2026-04-01",
    deadline: "2026-04-25",
    daysUntilDeadline: 7,
    applicantCount: 6,
    verified: true,
    timeline: "4–6 weeks (structured corporate process)",
    hiringProcess: [
      { step: 1, label: "Application Review", description: "HR screens all applications." },
      { step: 2, label: "Written Assessment", description: "SQL + analytical reasoning test online." },
      { step: 3, label: "HR Interview", description: "30-min HR call." },
      { step: 4, label: "Technical Interview", description: "Meet the data team." },
      { step: 5, label: "Offer", description: "Formal offer letter within 5 days." },
    ],
  },
  {
    id: "j6",
    orgId: "o1",
    orgName: "TechMK",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TM",
    title: "Full-Stack Developer",
    type: "full-time",
    location: "Skopje, MK",
    remote: true,
    salary: "€1,200–1,800/mo",
    description:
      "Join as a full-stack developer on our core product. You'll own features end to end — from database schema to React UI. Small team, high trust, real impact.",
    requirements: [
      "2+ years React experience",
      "Node.js / Express backend",
      "PostgreSQL or MySQL",
      "Passion for clean, maintainable code",
    ],
    tags: ["React", "Node.js", "Full-Stack", "PostgreSQL", "TypeScript"],
    status: "open",
    postedAt: "2026-04-14",
    deadline: "2026-05-10",
    daysUntilDeadline: 22,
    applicantCount: 33,
    verified: true,
    featured: true,
    timeline: "2–3 weeks from application to start",
    hiringProcess: [
      { step: 1, label: "CV + GitHub Review", description: "We check your code, not just your CV." },
      { step: 2, label: "Take-home Project", description: "Small full-stack feature, ~4–6 hours." },
      { step: 3, label: "Code Review Call", description: "Walk us through your solution." },
      { step: 4, label: "Offer", description: "We decide within 3 days of the call." },
    ],
  },
  {
    id: "j7",
    orgId: "o3",
    orgName: "Sorsix",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=SO",
    title: "DevOps Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€350–500/mo",
    description:
      "Learn cloud infrastructure, CI/CD pipelines, and container orchestration while supporting real client projects. Great entry point into the DevOps world with strong mentorship.",
    requirements: [
      "Linux basics",
      "Curiosity about cloud (AWS/GCP/Azure)",
      "Scripting knowledge (bash or Python)",
      "No prior DevOps experience required",
    ],
    tags: ["DevOps", "Docker", "AWS", "CI/CD", "Linux", "Python"],
    status: "open",
    postedAt: "2026-04-11",
    deadline: "2026-05-05",
    daysUntilDeadline: 17,
    applicantCount: 9,
    verified: true,
    timeline: "3–4 weeks from application",
    hiringProcess: [
      { step: 1, label: "Application Review", description: "CV and motivation letter screened." },
      { step: 2, label: "Technical Chat", description: "30-min call to test your Linux basics." },
      { step: 3, label: "Offer", description: "Fast close — usually within 2 weeks." },
    ],
  },
  {
    id: "j8",
    orgId: "o4",
    orgName: "Brainster",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=BR",
    title: "Content & Marketing Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€250–400/mo",
    description:
      "Create content for social media, email campaigns, and the Brainster blog. Work closely with the growth team on campaigns that reach 50k+ students across the Balkans.",
    requirements: [
      "Strong writing skills in English and Macedonian",
      "Creative mindset",
      "Familiarity with social media platforms",
      "Bonus: Canva or basic design skills",
    ],
    tags: ["Marketing", "Content", "Social Media", "Growth", "Copywriting"],
    status: "open",
    postedAt: "2026-04-09",
    deadline: "2026-04-27",
    daysUntilDeadline: 9,
    applicantCount: 14,
    verified: true,
    timeline: "1–2 weeks, fast process",
    hiringProcess: [
      { step: 1, label: "CV + Writing Sample", description: "Send 1–2 writing samples with your application." },
      { step: 2, label: "Brief Task", description: "Write a short post for our target audience." },
      { step: 3, label: "Team Chat", description: "Informal 20-min call with the team." },
      { step: 4, label: "Offer", description: "Usually within 10 days of applying." },
    ],
  },
  {
    id: "j9",
    orgId: "o5",
    orgName: "Netcetera",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=NC",
    title: "QA Engineer Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€400–550/mo",
    description:
      "Join the QA team working on high-stakes fintech products. Learn test automation, write real test cases, and help ensure quality on apps used by hundreds of thousands of people.",
    requirements: [
      "Basic programming knowledge",
      "Analytical mindset",
      "Familiarity with testing concepts",
      "Detail-oriented",
    ],
    tags: ["QA", "Testing", "Selenium", "Java", "Automation"],
    status: "open",
    postedAt: "2026-04-13",
    deadline: "2026-05-10",
    daysUntilDeadline: 22,
    applicantCount: 7,
    verified: true,
    timeline: "3–4 weeks from application to start",
    hiringProcess: [
      { step: 1, label: "CV Review", description: "HR screens within 5 days." },
      { step: 2, label: "Technical Test", description: "Online logic + basic coding test." },
      { step: 3, label: "Interview", description: "Meet the QA lead and HR." },
      { step: 4, label: "Offer", description: "Decision within one week of interview." },
    ],
  },
  {
    id: "j10",
    orgId: "o2",
    orgName: "Alkaloid",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=AL",
    title: "Software Developer Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€450–600/mo",
    description:
      "Work alongside senior developers on internal tools and systems that support pharmaceutical manufacturing. Python and web stack — meaningful work in a well-resourced company.",
    requirements: [
      "Python or JavaScript basics",
      "Understanding of databases",
      "Problem-solving attitude",
      "Available full-time",
    ],
    tags: ["Python", "JavaScript", "Backend", "SQL", "REST"],
    status: "open",
    postedAt: "2026-04-07",
    deadline: "2026-05-01",
    daysUntilDeadline: 13,
    applicantCount: 11,
    verified: true,
    timeline: "4–6 weeks (structured process)",
    hiringProcess: [
      { step: 1, label: "Application", description: "CV and motivation letter." },
      { step: 2, label: "Online Test", description: "Technical aptitude and coding basics." },
      { step: 3, label: "HR Interview", description: "Personality and culture fit." },
      { step: 4, label: "Technical Interview", description: "With the dev team lead." },
      { step: 5, label: "Offer", description: "Formal offer within 5 business days." },
    ],
  },
  {
    id: "j11",
    orgId: "o1",
    orgName: "TechMK",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TM",
    title: "React Native Developer Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€400–600/mo",
    description:
      "Help build our mobile app from scratch using React Native. You'll work with the same web team, share components, and ship features to both iOS and Android simultaneously.",
    requirements: [
      "React knowledge required",
      "Basic mobile development understanding",
      "TypeScript preferred",
      "Passion for cross-platform development",
    ],
    tags: ["React Native", "TypeScript", "Mobile", "iOS", "Android", "React"],
    status: "open",
    postedAt: "2026-04-15",
    deadline: "2026-05-12",
    daysUntilDeadline: 24,
    applicantCount: 5,
    verified: true,
    timeline: "2 weeks from application to offer",
    hiringProcess: [
      { step: 1, label: "CV Review", description: "Quick review, 1–2 days." },
      { step: 2, label: "Intro Call", description: "20-min call with the tech lead." },
      { step: 3, label: "Small Task", description: "Build a simple React Native screen." },
      { step: 4, label: "Offer", description: "Fast close — we don't drag it out." },
    ],
  },
  {
    id: "j12",
    orgId: "o4",
    orgName: "Brainster",
    orgLogo: "https://api.dicebear.com/7.x/initials/svg?seed=BR",
    title: "Product Management Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€300–450/mo",
    description:
      "Shadow and support the PM team while owning real product tasks — writing specs, running user research sessions, and helping prioritize the roadmap for our edtech platform.",
    requirements: [
      "Strong written and verbal communication",
      "Analytical mindset",
      "Interest in product and user experience",
      "Familiarity with tools like Notion, Jira, or Trello",
    ],
    tags: ["Product", "PM", "Research", "Strategy", "EdTech", "Figma"],
    status: "open",
    postedAt: "2026-04-16",
    deadline: "2026-05-03",
    daysUntilDeadline: 15,
    applicantCount: 8,
    verified: true,
    timeline: "1–2 weeks from application to decision",
    hiringProcess: [
      { step: 1, label: "Application Review", description: "CV + motivation screened in 2–3 days." },
      { step: 2, label: "Case Study Task", description: "Brief product thinking exercise." },
      { step: 3, label: "Team Interview", description: "Meet the product team." },
      { step: 4, label: "Offer", description: "Decision within 1 week of interview." },
    ],
  },
];

// Compute match score for a student based on skill overlap
export function computeMatchScore(jobTags: string[], studentSkills: string[]): number {
  if (!jobTags.length) return 0;
  const normalizedSkills = studentSkills.map((s) => s.toLowerCase());
  const normalizedTags = jobTags.map((t) => t.toLowerCase());
  const matches = normalizedTags.filter((t) => normalizedSkills.includes(t)).length;
  const raw = Math.round((matches / normalizedTags.length) * 100);
  // Minimum floor of 40 so no card looks totally irrelevant in the demo
  return Math.max(40, Math.min(raw + 15, 99));
}

export const mockApplications: Application[] = [
  {
    id: "a1",
    jobId: "aaaaaaaa-0000-0000-0000-000000000001",
    studentId: "s1",
    studentName: "Alex Petrov",
    studentEmail: "alex.petrov@students.ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Computer Science",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    coverNote:
      "I'm really excited about this role. I've been building React apps for 2 years and love working on products that users love.",
    status: "reviewing",
    appliedAt: "2026-04-11",
    updatedAt: "2026-04-13",
  },
  {
    id: "a2",
    jobId: "aaaaaaaa-0000-0000-0000-000000000003",
    studentId: "s1",
    studentName: "Alex Petrov",
    studentEmail: "alex.petrov@students.ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Computer Science",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    coverNote: "Mobile is my next frontier — I've been learning Swift on the side.",
    status: "applied",
    appliedAt: "2026-04-14",
    updatedAt: "2026-04-14",
  },
  {
    id: "a3",
    jobId: "aaaaaaaa-0000-0000-0000-000000000004",
    studentId: "s1",
    studentName: "Alex Petrov",
    studentEmail: "alex.petrov@students.ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Computer Science",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    status: "interview",
    appliedAt: "2026-04-12",
    updatedAt: "2026-04-15",
  },
];

// Extra applicants for org dashboard
export const mockOrgApplicants: Application[] = [
  {
    id: "oa1",
    jobId: "aaaaaaaa-0000-0000-0000-000000000001",
    studentId: "s2",
    studentName: "Sara Nikolovska",
    studentEmail: "sara.n@students.ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Software Engineering",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sara",
    coverNote: "Frontend is my passion — I've shipped 3 side projects using React.",
    status: "reviewing",
    appliedAt: "2026-04-11",
    updatedAt: "2026-04-13",
  },
  {
    id: "oa2",
    jobId: "aaaaaaaa-0000-0000-0000-000000000001",
    studentId: "s3",
    studentName: "Nikola Ristevski",
    studentEmail: "nikola.r@finki.ukim.mk",
    studentUniversity: "Faculty of Computer Science (FINKI)",
    studentMajor: "Computer Science",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nikola",
    coverNote: "Strong TypeScript skills, looking to grow in a product-focused company.",
    status: "applied",
    appliedAt: "2026-04-12",
    updatedAt: "2026-04-12",
  },
  {
    id: "oa3",
    jobId: "aaaaaaaa-0000-0000-0000-000000000001",
    studentId: "s4",
    studentName: "Elena Trajkoska",
    studentEmail: "elena.t@students.ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Information Systems",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elena",
    status: "interview",
    appliedAt: "2026-04-10",
    updatedAt: "2026-04-15",
  },
  {
    id: "oa4",
    jobId: "aaaaaaaa-0000-0000-0000-000000000006",
    studentId: "s5",
    studentName: "Marko Dimitrov",
    studentEmail: "marko.d@finki.ukim.mk",
    studentUniversity: "Faculty of Computer Science (FINKI)",
    studentMajor: "Computer Science",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marko",
    coverNote: "3 years of React, 2 years of Node. Looking for a place to grow.",
    status: "offered",
    appliedAt: "2026-04-14",
    updatedAt: "2026-04-16",
  },
  {
    id: "oa5",
    jobId: "aaaaaaaa-0000-0000-0000-000000000006",
    studentId: "s6",
    studentName: "Iva Spasovska",
    studentEmail: "iva.s@students.ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Software Engineering",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Iva",
    status: "rejected",
    appliedAt: "2026-04-14",
    updatedAt: "2026-04-16",
  },
];
