import { Job, Student, Organization, Application, OrgReview } from "@/types";

export const mockStudent: Student = {
  id: "22222222-2222-2222-2222-222222222222",
  name: "Alex Petrov",
  email: "alex.petrov@candidates.ukim.mk",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
  university: "Ss. Cyril and Methodius University",
  major: "Computer Science",
  year: "3rd Year",
  gpa: "9.2",
  bio: "Early‑career engineer interested in building products that matter. Looking for hands‑on roles.",
  skills: ["React", "TypeScript", "Python", "Node.js", "Figma"],
  projects: [
    {
      id: "p1",
      name: "Campus Events Finder",
      description: "Built a web app for candidates to discover campus events and RSVP.",
      link: "https://github.com/alexpetrov/campus-events",
      skills: ["React", "TypeScript", "Supabase"],
    },
    {
      id: "p2",
      name: "Study Buddy",
      description: "Matched candidates into study groups using a lightweight matching algorithm.",
      link: "https://github.com/alexpetrov/study-buddy",
      skills: ["Node.js", "PostgreSQL", "UX"],
    },
  ],
  interests: ["Product design", "EdTech", "AI tools"],
  availability: "Available 20–30h/week, June–September",
  linkedin: "linkedin.com/in/alexpetrov",
  github: "github.com/alexpetrov",
};

export const mockOrg: Organization = {
  id: "11111111-1111-1111-1111-111111111111",
  name: "TechMK",
  email: "hr@techmk.com",
  avatar: "/techmk.png",
  industry: "Software",
  size: "50–200",
  location: "Skopje, MK",
  website: "techmk.com",
  description:
    "TechMK is a fast-growing software company building SaaS products for the Balkans market.",
  founded: "2018",
  verified: true,
  hiresCount: 23,
  responseTime: "Usually responds in 2–3 days",
  activeThisWeek: true,
};

export const mockOrganizations: Organization[] = [
  mockOrg,
  {
    id: "o2",
    name: "Alkaloid",
    logo: "/alkaloid.png",
    email: "careers@alkaloid.com.mk",
    industry: "Pharma & Tech",
    size: "1000+",
    location: "Skopje, MK",
    website: "alkaloid.com.mk",
    description: "Leading pharmaceutical and technology company in the region. We combine deep scientific expertise with modern software to build healthcare solutions used across Southeast Europe.",
    founded: "1936",
    verified: true,
    hiresCount: 61,
    responseTime: "Usually responds in 5–7 days",
    activeThisWeek: true,
  },
  {
    id: "o3",
    name: "Sorsix",
    logo: "/sorsix.jpeg",
    email: "jobs@sorsix.com",
    industry: "Software",
    size: "50–200",
    location: "Skopje, MK",
    website: "sorsix.com",
    description: "Software consulting and product development for global clients. We build backend systems, APIs, and infrastructure for companies across the US and Europe.",
    founded: "2012",
    verified: true,
    hiresCount: 34,
    responseTime: "Usually responds in 3–5 days",
    activeThisWeek: false,
  },
  {
    id: "o4",
    name: "Brainster",
    logo: "/brainster.png",
    email: "careers@brainster.co",
    industry: "EdTech",
    size: "10–50",
    location: "Skopje, MK",
    website: "brainster.co",
    description: "The leading tech education company in the Western Balkans. We run bootcamps, academies, and corporate training programs that have launched over 3,000 careers in tech.",
    founded: "2017",
    verified: true,
    hiresCount: 18,
    responseTime: "Usually responds in 2–4 days",
    activeThisWeek: true,
  },
  {
    id: "o5",
    name: "Netcetera",
    logo: "/netcetera.png",
    email: "careers@netcetera.com",
    industry: "Software",
    size: "500–1000",
    location: "Skopje, MK",
    website: "netcetera.com",
    description: "Swiss software company with a major development hub in Macedonia. We build secure, high-quality digital products for banking, transport, and retail clients worldwide.",
    founded: "1999",
    verified: true,
    hiresCount: 89,
    responseTime: "Usually responds in 1–2 weeks",
    activeThisWeek: true,
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    orgId: "o1",
    orgName: "TechMK",
    orgLogo: "/techmk.png",
    title: "Frontend Engineering Intern",
    titleMk: "Практикант за Frontend инженерство",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€400–600/mo",
    description:
      "Join our product team to build beautiful, fast web interfaces. You'll work directly with senior engineers on real features shipped to thousands of users. No ticket monkey work — you'll own small features end to end.",
    descriptionMk:
      "Придружи се на продукт тимот за да изградиш брзи и елегантни веб интерфејси. Ќе работиш директно со сениор инженери на функции што се користат од илјадници корисници. Без ситни задачи — ќе водиш мали функционалности од почеток до крај.",
    requirements: [
      "Experience with React or Vue",
      "Basic TypeScript knowledge",
      "Eye for design and UX",
      "Available 20–40h/week",
    ],
    tags: ["React", "TypeScript", "Tailwind", "Frontend"],
    status: "open",
    postedAt: "2026-04-10",
    deadline: "2026-05-01",
    daysUntilDeadline: 13,
    applicantCount: 12,
    verified: true,
    featured: true,
    timeline: "2–3 weeks from application to offer",
    hiringProcess: [
      { step: 1, label: "CV Review", description: "We review your profile within 3 days." },
      { step: 2, label: "Short Intro Call", description: "15-min call to get to know you." },
      { step: 3, label: "Take-home Task", description: "Small frontend task, ~2–3 hours." },
      { step: 4, label: "Offer", description: "We move fast — decision within a week." },
    ],
  },
  {
    id: "j2",
    orgId: "o3",
    orgName: "Sorsix",
    orgLogo: "/sorsix.jpeg",
    title: "Backend Developer Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€350–500/mo",
    description:
      "Work on backend services powering enterprise clients across Europe. You'll learn about scalable architecture, REST APIs, and cloud infrastructure while shipping real code to production.",
    requirements: [
      "Java or Kotlin basics",
      "Understanding of REST APIs",
      "Comfortable with Git",
      "Eager to learn",
    ],
    tags: ["Java", "Spring Boot", "Backend", "REST", "AWS"],
    status: "open",
    postedAt: "2026-04-08",
    deadline: "2026-04-30",
    daysUntilDeadline: 12,
    applicantCount: 8,
    verified: true,
    timeline: "3–4 weeks end to end",
    hiringProcess: [
      { step: 1, label: "Application Review", description: "CV and GitHub screened within 5 days." },
      { step: 2, label: "Technical Interview", description: "45-min technical call with the team." },
      { step: 3, label: "Team Interview", description: "Culture and fit conversation." },
      { step: 4, label: "Offer", description: "Decision communicated within 3 days." },
    ],
  },
  {
    id: "j3",
    orgId: "o5",
    orgName: "Netcetera",
    orgLogo: "/netcetera.png",
    title: "Mobile Developer Intern (iOS/Android)",
    titleMk: "Практикант за мобилен развој (iOS/Android)",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€500–700/mo",
    description:
      "Build real mobile features for millions of users across Europe. You'll be embedded in a cross-functional team from day one, working on apps used in banking and fintech.",
    descriptionMk:
      "Гради реални мобилни функционалности за милиони корисници низ Европа. Од првиот ден ќе бидеш дел од крос‑функционален тим и ќе работиш на апликации за банкарство и финтек.",
    requirements: [
      "Basic Swift or Kotlin experience",
      "Passion for mobile UX",
      "Strong fundamentals in OOP",
      "Available full-time",
    ],
    tags: ["iOS", "Android", "Swift", "Kotlin", "Mobile"],
    status: "open",
    postedAt: "2026-04-05",
    deadline: "2026-05-15",
    daysUntilDeadline: 27,
    applicantCount: 24,
    verified: true,
    featured: true,
    timeline: "3–5 weeks from first contact to start",
    hiringProcess: [
      { step: 1, label: "CV Screen", description: "HR reviews within 7 days." },
      { step: 2, label: "Technical Task", description: "Small mobile coding task, ~4 hours." },
      { step: 3, label: "Panel Interview", description: "Technical + HR panel, 1 hour." },
      { step: 4, label: "Offer & Onboarding", description: "Start within 2 weeks of offer." },
    ],
  },
  {
    id: "j4",
    orgId: "o4",
    orgName: "Brainster",
    orgLogo: "/brainster.png",
    title: "UX/UI Design Intern",
    titleMk: "Практикант за UX/UI дизајн",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€300–450/mo",
    description:
      "Help shape the learning experience for thousands of candidates. Work in Figma, run user interviews, and iterate on designs weekly. Your work ships — no mockups sitting in a drawer.",
    descriptionMk:
      "Помогни да го обликуваш искуството за учење на илјадници кандидати. Работи во Figma, води кориснички интервјуа и подобрувај дизајни секоја недела. Твојата работа се објавува — без mockups во фиока.",
    requirements: [
      "Figma proficiency",
      "Portfolio of UI work (2+ projects)",
      "Understanding of user-centered design",
      "Bonus: basic HTML/CSS",
    ],
    tags: ["Figma", "UX", "UI", "Design", "EdTech", "Prototyping"],
    status: "open",
    postedAt: "2026-04-12",
    deadline: "2026-04-28",
    daysUntilDeadline: 10,
    applicantCount: 19,
    verified: true,
    timeline: "1–2 weeks from application to start",
    hiringProcess: [
      { step: 1, label: "Portfolio Review", description: "We look at your Figma work within 3 days." },
      { step: 2, label: "Design Challenge", description: "Short redesign exercise, ~2 hours." },
      { step: 3, label: "Offer", description: "Fast process — usually done in under 2 weeks." },
    ],
    interviewInsights: {
      intro: "These insights help you prepare for the upcoming interview based on this role's hiring process.",
      interviewQuestions: [
        "Walk us through a recent UX project and the decisions you made.",
        "How do you approach user research when time is limited?",
        "Tell us about a time you collaborated with engineers to ship a design.",
        "What design systems or accessibility principles do you follow?",
      ],
      preparationTips: [
        "Review the role requirements and map them to 2–3 concrete examples.",
        "Prepare a short walkthrough of your portfolio, focusing on impact and tradeoffs.",
        "Be ready to explain your design process and how you validate decisions.",
        "Practice communicating constraints and how you prioritize feedback.",
      ],
      interviewStages: [
        "Round 1: Portfolio review with the design lead (30–40 min)",
        "Round 2: Short design challenge discussion (45–60 min)",
      ],
    },
    interviewInsightsMk: {
      intro: "Овие увиди ти помагаат да се подготвиш за претстојното интервју според процесот за оваа улога.",
      interviewQuestions: [
        "Раскажи ни за последен UX проект и клучните одлуки што ги донесе.",
        "Како пристапуваш кон корисничко истражување кога имаш ограничено време?",
        "Опиши ситуација кога соработуваше со инженери за да испорачаш дизајн.",
        "Кои дизајн системи или принципи за пристапност ги следиш?",
      ],
      preparationTips: [
        "Поврзи ги барањата на улогата со 2–3 конкретни примери од твојата работа.",
        "Подготви кратка прошетка низ портфолиото, со фокус на резултат и компромиси.",
        "Објасни го твојот процес и како ги валидираш дизајнерските одлуки.",
        "Вежбај јасна комуникација за ограничувања и приоритизација на фидбек.",
      ],
      interviewStages: [
        "Прва рунда: Преглед на портфолио со дизајн лидер (30–40 мин)",
        "Втора рунда: Разговор за краток дизајн предизвик (45–60 мин)",
      ],
    },
  },
  {
    id: "j5",
    orgId: "o2",
    orgName: "Alkaloid",
    orgLogo: "/alkaloid.png",
    title: "Data Analyst Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€400–550/mo",
    description:
      "Analyze production and sales data to support business decisions across the company. Work with SQL, Python, and internal BI tools on datasets that drive million-euro decisions.",
    requirements: [
      "SQL basics",
      "Python or R for data analysis",
      "Strong analytical thinking",
      "Excel proficiency",
    ],
    tags: ["SQL", "Python", "Data", "Analytics", "BI", "Excel"],
    status: "open",
    postedAt: "2026-04-01",
    deadline: "2026-04-25",
    daysUntilDeadline: 7,
    applicantCount: 6,
    verified: true,
    timeline: "4–6 weeks (structured corporate process)",
    hiringProcess: [
      { step: 1, label: "Application Review", description: "HR screens all applications." },
      { step: 2, label: "Written Assessment", description: "SQL + analytical reasoning test online." },
      { step: 3, label: "HR Interview", description: "30-min HR call." },
      { step: 4, label: "Technical Interview", description: "Meet the data team." },
      { step: 5, label: "Offer", description: "Formal offer letter within 5 days." },
    ],
  },
  {
    id: "j6",
    orgId: "o1",
    orgName: "TechMK",
    orgLogo: "/techmk.png",
    title: "Full-Stack Developer",
    type: "full-time",
    location: "Skopje, MK",
    remote: true,
    salary: "€1,200–1,800/mo",
    description:
      "Join as a full-stack developer on our core product. You'll own features end to end — from database schema to React UI. Small team, high trust, real impact.",
    requirements: [
      "2+ years React experience",
      "Node.js / Express backend",
      "PostgreSQL or MySQL",
      "Passion for clean, maintainable code",
    ],
    tags: ["React", "Node.js", "Full-Stack", "PostgreSQL", "TypeScript"],
    status: "open",
    postedAt: "2026-04-14",
    deadline: "2026-05-10",
    daysUntilDeadline: 22,
    applicantCount: 33,
    verified: true,
    featured: true,
    timeline: "2–3 weeks from application to start",
    hiringProcess: [
      { step: 1, label: "CV + GitHub Review", description: "We check your code, not just your CV." },
      { step: 2, label: "Take-home Project", description: "Small full-stack feature, ~4–6 hours." },
      { step: 3, label: "Code Review Call", description: "Walk us through your solution." },
      { step: 4, label: "Offer", description: "We decide within 3 days of the call." },
    ],
  },
  {
    id: "j7",
    orgId: "o3",
    orgName: "Sorsix",
    orgLogo: "/sorsix.jpeg",
    title: "DevOps Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€350–500/mo",
    description:
      "Learn cloud infrastructure, CI/CD pipelines, and container orchestration while supporting real client projects. Great entry point into the DevOps world with strong mentorship.",
    requirements: [
      "Linux basics",
      "Curiosity about cloud (AWS/GCP/Azure)",
      "Scripting knowledge (bash or Python)",
      "No prior DevOps experience required",
    ],
    tags: ["DevOps", "Docker", "AWS", "CI/CD", "Linux", "Python"],
    status: "open",
    postedAt: "2026-04-11",
    deadline: "2026-05-05",
    daysUntilDeadline: 17,
    applicantCount: 9,
    verified: true,
    timeline: "3–4 weeks from application",
    hiringProcess: [
      { step: 1, label: "Application Review", description: "CV and motivation letter screened." },
      { step: 2, label: "Technical Chat", description: "30-min call to test your Linux basics." },
      { step: 3, label: "Offer", description: "Fast close — usually within 2 weeks." },
    ],
  },
  {
    id: "j8",
    orgId: "o4",
    orgName: "Brainster",
    orgLogo: "/brainster.png",
    title: "Content & Marketing Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€250–400/mo",
    description:
      "Create content for social media, email campaigns, and the Brainster blog. Work closely with the growth team on campaigns that reach 50k+ candidates across the Balkans.",
    requirements: [
      "Strong writing skills in English and Macedonian",
      "Creative mindset",
      "Familiarity with social media platforms",
      "Bonus: Canva or basic design skills",
    ],
    tags: ["Marketing", "Content", "Social Media", "Growth", "Copywriting"],
    status: "open",
    postedAt: "2026-04-09",
    deadline: "2026-04-27",
    daysUntilDeadline: 9,
    applicantCount: 14,
    verified: true,
    timeline: "1–2 weeks, fast process",
    hiringProcess: [
      { step: 1, label: "CV + Writing Sample", description: "Send 1–2 writing samples with your application." },
      { step: 2, label: "Brief Task", description: "Write a short post for our target audience." },
      { step: 3, label: "Team Chat", description: "Informal 20-min call with the team." },
      { step: 4, label: "Offer", description: "Usually within 10 days of applying." },
    ],
  },
  {
    id: "j9",
    orgId: "o5",
    orgName: "Netcetera",
    orgLogo: "/netcetera.png",
    title: "QA Engineer Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€400–550/mo",
    description:
      "Join the QA team working on high-stakes fintech products. Learn test automation, write real test cases, and help ensure quality on apps used by hundreds of thousands of people.",
    requirements: [
      "Basic programming knowledge",
      "Analytical mindset",
      "Familiarity with testing concepts",
      "Detail-oriented",
    ],
    tags: ["QA", "Testing", "Selenium", "Java", "Automation"],
    status: "open",
    postedAt: "2026-04-13",
    deadline: "2026-05-10",
    daysUntilDeadline: 22,
    applicantCount: 7,
    verified: true,
    timeline: "3–4 weeks from application to start",
    hiringProcess: [
      { step: 1, label: "CV Review", description: "HR screens within 5 days." },
      { step: 2, label: "Technical Test", description: "Online logic + basic coding test." },
      { step: 3, label: "Interview", description: "Meet the QA lead and HR." },
      { step: 4, label: "Offer", description: "Decision within one week of interview." },
    ],
  },
  {
    id: "j10",
    orgId: "o2",
    orgName: "Alkaloid",
    orgLogo: "/alkaloid.png",
    title: "Software Developer Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: false,
    salary: "€450–600/mo",
    description:
      "Work alongside senior developers on internal tools and systems that support pharmaceutical manufacturing. Python and web stack — meaningful work in a well-resourced company.",
    requirements: [
      "Python or JavaScript basics",
      "Understanding of databases",
      "Problem-solving attitude",
      "Available full-time",
    ],
    tags: ["Python", "JavaScript", "Backend", "SQL", "REST"],
    status: "open",
    postedAt: "2026-04-07",
    deadline: "2026-05-01",
    daysUntilDeadline: 13,
    applicantCount: 11,
    verified: true,
    timeline: "4–6 weeks (structured process)",
    hiringProcess: [
      { step: 1, label: "Application", description: "CV and motivation letter." },
      { step: 2, label: "Online Test", description: "Technical aptitude and coding basics." },
      { step: 3, label: "HR Interview", description: "Personality and culture fit." },
      { step: 4, label: "Technical Interview", description: "With the dev team lead." },
      { step: 5, label: "Offer", description: "Formal offer within 5 business days." },
    ],
  },
  {
    id: "j11",
    orgId: "o1",
    orgName: "TechMK",
    orgLogo: "/techmk.png",
    title: "React Native Developer Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€400–600/mo",
    description:
      "Help build our mobile app from scratch using React Native. You'll work with the same web team, share components, and ship features to both iOS and Android simultaneously.",
    requirements: [
      "React knowledge required",
      "Basic mobile development understanding",
      "TypeScript preferred",
      "Passion for cross-platform development",
    ],
    tags: ["React Native", "TypeScript", "Mobile", "iOS", "Android", "React"],
    status: "open",
    postedAt: "2026-04-15",
    deadline: "2026-05-12",
    daysUntilDeadline: 24,
    applicantCount: 5,
    verified: true,
    timeline: "2 weeks from application to offer",
    hiringProcess: [
      { step: 1, label: "CV Review", description: "Quick review, 1–2 days." },
      { step: 2, label: "Intro Call", description: "20-min call with the tech lead." },
      { step: 3, label: "Small Task", description: "Build a simple React Native screen." },
      { step: 4, label: "Offer", description: "Fast close — we don't drag it out." },
    ],
  },
  {
    id: "j12",
    orgId: "o4",
    orgName: "Brainster",
    orgLogo: "/brainster.png",
    title: "Product Management Intern",
    type: "internship",
    location: "Skopje, MK",
    remote: true,
    salary: "€300–450/mo",
    description:
      "Shadow and support the PM team while owning real product tasks — writing specs, running user research sessions, and helping prioritize the roadmap for our edtech platform.",
    requirements: [
      "Strong written and verbal communication",
      "Analytical mindset",
      "Interest in product and user experience",
      "Familiarity with tools like Notion, Jira, or Trello",
    ],
    tags: ["Product", "PM", "Research", "Strategy", "EdTech", "Figma"],
    status: "open",
    postedAt: "2026-04-16",
    deadline: "2026-05-03",
    daysUntilDeadline: 15,
    applicantCount: 8,
    verified: true,
    timeline: "1–2 weeks from application to decision",
    hiringProcess: [
      { step: 1, label: "Application Review", description: "CV + motivation screened in 2–3 days." },
      { step: 2, label: "Case Study Task", description: "Brief product thinking exercise." },
      { step: 3, label: "Team Interview", description: "Meet the product team." },
      { step: 4, label: "Offer", description: "Decision within 1 week of interview." },
    ],
  },
];

export const mockApplications: Application[] = [
  {
    id: "a1",
    jobId: "j1",
    studentId: "s1",
    studentName: "Alex Petrov",
    studentEmail: "alex.petrov@candidates.ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Computer Science",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    coverNote:
      "I'm really excited about this role. I've been building React apps for 2 years and love working on products that users love.",
    status: "reviewing",
    appliedAt: "2026-04-11",
    updatedAt: "2026-04-13",
  },
  {
    id: "a2",
    jobId: "j3",
    studentId: "s1",
    studentName: "Alex Petrov",
    studentEmail: "alex.petrov@candidates.ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Computer Science",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    coverNote: "Mobile is my next frontier — I've been learning Swift on the side.",
    status: "applied",
    appliedAt: "2026-04-14",
    updatedAt: "2026-04-14",
  },
  {
    id: "a3",
    jobId: "j4",
    studentId: "s1",
    studentName: "Alex Petrov",
    studentEmail: "alex.petrov@candidates.ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Computer Science",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    status: "interview_invited",
    appliedAt: "2026-04-12",
    updatedAt: "2026-04-15",
  },
];

// Extra applicants for org dashboard
export const mockOrgApplicants: Application[] = [
  {
    id: "oa1",
    jobId: "j1",
    orgId: "11111111-1111-1111-1111-111111111111",
    studentId: "s2",
    studentName: "Sara Nikolovska",
    studentEmail: "sara.n@ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Software Engineering",
    studentYear: "4th Year",
    studentGpa: "9.5",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sara",
    studentSkills: ["React", "TypeScript", "CSS", "Vue.js", "Figma"],
    studentProjects: [
      { id: "sp1", name: "Portfolio CMS", description: "Custom headless CMS built with React and Supabase. Used by 3 freelancers.", skills: ["React", "TypeScript", "Supabase"] },
      { id: "sp2", name: "UI Component Library", description: "Accessible component library with Storybook docs.", skills: ["React", "CSS", "Figma"] },
    ],
    studentInterests: ["Design systems", "Accessibility", "Open source"],
    studentAvailability: "Full-time from June 2026",
    studentBio: "Frontend engineer focused on accessible, pixel-perfect UIs. Love design systems and clean APIs.",
    studentLinkedin: "linkedin.com/in/sara-nikolovska",
    studentGithub: "github.com/saranikolovska",
    studentIknowVerified: true,
    coverNote: "Frontend is my passion — I've shipped 3 side projects using React.",
    status: "reviewing",
    appliedAt: "2026-04-11",
    updatedAt: "2026-04-13",
  },
  {
    id: "oa2",
    jobId: "j1",
    orgId: "11111111-1111-1111-1111-111111111111",
    studentId: "s3",
    studentName: "Nikola Ristevski",
    studentEmail: "nikola.r@finki.ukim.mk",
    studentUniversity: "Faculty of Computer Science (FINKI)",
    studentMajor: "Computer Science",
    studentYear: "3rd Year",
    studentGpa: "8.8",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nikola",
    studentSkills: ["TypeScript", "Node.js", "Python", "PostgreSQL", "Docker"],
    studentProjects: [
      { id: "sp3", name: "REST API Boilerplate", description: "Production-ready Node.js REST API with auth, rate limiting, and OpenAPI docs.", skills: ["Node.js", "TypeScript", "PostgreSQL"] },
    ],
    studentInterests: ["Backend architecture", "DevOps", "Open source tooling"],
    studentAvailability: "Part-time 20h/week, available immediately",
    studentBio: "Backend-first developer who cares about correctness and observability. Comfortable with the full stack when needed.",
    studentLinkedin: "linkedin.com/in/nikola-ristevski",
    studentGithub: "github.com/nristevski",
    studentIknowVerified: false,
    coverNote: "Strong TypeScript skills, looking to grow in a product-focused company.",
    status: "applied",
    appliedAt: "2026-04-12",
    updatedAt: "2026-04-12",
  },
  {
    id: "oa3",
    jobId: "j1",
    orgId: "11111111-1111-1111-1111-111111111111",
    studentId: "s4",
    studentName: "Elena Trajkoska",
    studentEmail: "elena.t@ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Information Systems",
    studentYear: "4th Year",
    studentGpa: "9.1",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elena",
    studentSkills: ["React", "TypeScript", "Java", "SQL", "Figma"],
    studentProjects: [
      { id: "sp4", name: "Student Dashboard", description: "University course tracker with calendar integration, used by 200+ students.", skills: ["React", "TypeScript", "SQL"] },
      { id: "sp5", name: "Alumni Network App", description: "Mobile-first app connecting FINKI alumni.", skills: ["React", "Java", "SQL"] },
    ],
    studentInterests: ["Product thinking", "EdTech", "UX research"],
    studentAvailability: "Full-time from July 2026",
    studentBio: "Full-stack leaning frontend. Interested in products that have educational impact.",
    studentLinkedin: "linkedin.com/in/elena-trajkoska",
    studentGithub: "github.com/elenatrajkoska",
    studentIknowVerified: true,
    status: "interview",
    appliedAt: "2026-04-10",
    updatedAt: "2026-04-15",
  },
  {
    id: "oa4",
    jobId: "j6",
    orgId: "11111111-1111-1111-1111-111111111111",
    studentId: "s5",
    studentName: "Marko Dimitrov",
    studentEmail: "marko.d@finki.ukim.mk",
    studentUniversity: "Faculty of Computer Science (FINKI)",
    studentMajor: "Computer Science",
    studentYear: "Masters",
    studentGpa: "9.7",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marko",
    studentSkills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS", "Docker"],
    studentProjects: [
      { id: "sp6", name: "SaaS Starter Kit", description: "Full-stack SaaS boilerplate with auth, billing, and multi-tenancy. 300+ GitHub stars.", skills: ["React", "Node.js", "PostgreSQL", "TypeScript"] },
      { id: "sp7", name: "Real-time Chat API", description: "WebSocket-based chat backend handling 1k concurrent connections.", skills: ["Node.js", "AWS", "Docker"] },
    ],
    studentInterests: ["Distributed systems", "Developer tooling", "Startups"],
    studentAvailability: "Full-time, available immediately",
    studentBio: "Senior-leaning full-stack engineer. Built and shipped multiple products end-to-end.",
    studentLinkedin: "linkedin.com/in/marko-dimitrov",
    studentGithub: "github.com/markodimitrov",
    studentIknowVerified: true,
    coverNote: "3 years of React, 2 years of Node. Looking for a place to grow.",
    status: "offered",
    appliedAt: "2026-04-14",
    updatedAt: "2026-04-16",
  },
  {
    id: "oa5",
    jobId: "j6",
    orgId: "11111111-1111-1111-1111-111111111111",
    studentId: "s6",
    studentName: "Iva Spasovska",
    studentEmail: "iva.s@ukim.mk",
    studentUniversity: "Ss. Cyril and Methodius University",
    studentMajor: "Software Engineering",
    studentYear: "3rd Year",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Iva",
    studentSkills: ["Python", "Django", "SQL", "REST"],
    studentProjects: [
      { id: "sp8", name: "E-commerce Backend", description: "Django REST API for a local store. Handles orders, inventory, payments.", skills: ["Python", "Django", "SQL"] },
    ],
    studentInterests: ["Backend", "Data engineering"],
    studentAvailability: "Part-time 15h/week",
    studentBio: "Backend developer with Python focus. Comfortable with REST APIs and relational databases.",
    studentIknowVerified: false,
    status: "rejected",
    appliedAt: "2026-04-14",
    updatedAt: "2026-04-16",
  },
  {
    id: "oa6",
    jobId: "j11",
    orgId: "11111111-1111-1111-1111-111111111111",
    studentId: "s7",
    studentName: "Petar Georgijev",
    studentEmail: "petar.g@finki.ukim.mk",
    studentUniversity: "Faculty of Computer Science (FINKI)",
    studentMajor: "Computer Science",
    studentYear: "3rd Year",
    studentGpa: "8.5",
    studentAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Petar",
    studentSkills: ["React", "React Native", "TypeScript", "Expo"],
    studentProjects: [
      { id: "sp9", name: "Habit Tracker App", description: "Cross-platform habit tracking app built with Expo. 500+ installs.", skills: ["React Native", "TypeScript", "Expo"] },
    ],
    studentInterests: ["Mobile UX", "Cross-platform development"],
    studentAvailability: "Full-time from June 2026",
    studentBio: "Mobile-first developer. React Native enthusiast shipping to iOS and Android simultaneously.",
    studentGithub: "github.com/petargeorgijev",
    studentIknowVerified: true,
    coverNote: "Been building React Native apps for 2 years. Expo is my daily driver.",
    status: "shortlisted",
    appliedAt: "2026-04-15",
    updatedAt: "2026-04-17",
  },
];

export const mockOrgReviews: OrgReview[] = [
  // TechMK (id: "11111111-1111-1111-1111-111111111111")
  {
    id: "r1",
    organizationId: "11111111-1111-1111-1111-111111111111",
    reviewerName: "Stefan M.",
    role: "Frontend Intern",
    rating: 5,
    reviewText: "One of the best internship experiences I've had. Real ownership from day one — I shipped features to production in my first week. The team was incredibly supportive and gave honest feedback.",
    isVerifiedWorker: true,
    createdAt: "2026-03-14",
  },
  {
    id: "r2",
    organizationId: "11111111-1111-1111-1111-111111111111",
    reviewerName: "Ana K.",
    role: "Full-stack Developer",
    rating: 4,
    reviewText: "Great culture and modern tech stack. The pace is fast but the team helps you keep up. Would have appreciated more structured onboarding, but overall a very positive experience.",
    isVerifiedWorker: true,
    createdAt: "2026-02-28",
  },
  {
    id: "r3",
    organizationId: "11111111-1111-1111-1111-111111111111",
    reviewerName: "Bojan T.",
    role: "Backend Intern",
    rating: 4,
    reviewText: "Solid company. Good mentors, interesting problems, reasonable hours. The internship was paid fairly for the region. I'd recommend it to any junior dev looking for real experience.",
    isVerifiedWorker: false,
    createdAt: "2026-01-10",
  },
  // Sorsix (id: "o3")
  {
    id: "r4",
    organizationId: "o3",
    reviewerName: "Maja R.",
    role: "Software Engineer Intern",
    rating: 5,
    reviewText: "Incredible learning environment. The codebase is well-maintained and the senior devs take time to explain the architecture. I learned more in 3 months here than in a year of university projects.",
    isVerifiedWorker: true,
    createdAt: "2026-03-01",
  },
  {
    id: "r5",
    organizationId: "o3",
    reviewerName: "Darko S.",
    role: "Java Developer Intern",
    rating: 3,
    reviewText: "Good technical exposure and international projects. The work is interesting but the onboarding process could be smoother. Communication between teams can sometimes be slow.",
    isVerifiedWorker: true,
    createdAt: "2025-12-20",
  },
  // Brainster (id: "o4")
  {
    id: "r6",
    organizationId: "o4",
    reviewerName: "Kristina V.",
    role: "Product Management Intern",
    rating: 5,
    reviewText: "Brainster gave me a front-row seat to how an edtech startup operates. I owned real tasks — user interviews, roadmap work, sprint planning. The team is sharp and moves fast.",
    isVerifiedWorker: true,
    createdAt: "2026-02-15",
  },
  {
    id: "r7",
    organizationId: "o4",
    reviewerName: "Lazar P.",
    role: "Marketing Intern",
    rating: 4,
    reviewText: "Energetic place with a strong mission. Lots of autonomy, which I appreciated. The role stretched me beyond my comfort zone in a good way. Great first job out of university.",
    isVerifiedWorker: false,
    createdAt: "2025-11-30",
  },
  // Netcetera (id: "o5")
  {
    id: "r8",
    organizationId: "o5",
    reviewerName: "Teodora G.",
    role: "QA Engineer Intern",
    rating: 4,
    reviewText: "Very professional environment. Swiss-level standards applied to everything — processes, code quality, documentation. You learn rigorous engineering practices here. Slightly slower-paced than startups but very stable.",
    isVerifiedWorker: true,
    createdAt: "2026-03-22",
  },
  {
    id: "r9",
    organizationId: "o5",
    reviewerName: "Ivan B.",
    role: "Backend Developer",
    rating: 5,
    reviewText: "The best company I've worked at in Macedonia. International clients, great tools, and a team that actually cares about quality. The code review culture alone is worth it.",
    isVerifiedWorker: true,
    createdAt: "2026-01-18",
  },
  // Alkaloid (id: "o2")
  {
    id: "r10",
    organizationId: "o2",
    reviewerName: "Vlatko N.",
    role: "Software Developer Intern",
    rating: 3,
    reviewText: "Large company feel — lots of process but also lots of resources. The tech stack is modern and the team was helpful. If you want startup pace this isn't it, but if you want stability and learning, it works.",
    isVerifiedWorker: true,
    createdAt: "2026-02-05",
  },
];
